#* Docker Compose version
version: '3.9'

#* All services to be used will be declared
services:

  #* Service name
  front:
    #* Image to use
    image: node:14.17.5
    init: true
    #* Directory where you will work
    working_dir: /home/dev
    #* Container name
    container_name: kinnil-cedar-front
    command: sh -c "npm i -g @angular/cli@13.0.0 && npm i && ng serve --port 4200 --host 0.0.0.0"
    #* Port exhibition
    ports:
      - 4200:4200
    #* Volume where information persists
    volumes:
      - .:/home/dev
    restart: unless-stopped