version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: DockerFile.back
    #* Volume where information persists
    volumes:
      - ./server:/home/dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 8080
      PORTQUECTEL: 3006
      PORTSOCKETIO: 3005
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx/config.nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email admin@pidelectronics.com --agree-tos --no-eff-email --staging -d api.maxxim.kinnil.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/kinnil/kinnil-feat-cedar/server/src/views/
      o: bind

networks:
  app-network:
    driver: bridge